name: SwiftLint
on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - 'QueenCam/.swiftlint.yml'
      - '**/*.swift'
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Debug changed files
        run: |
          echo "Base ref: ${{ github.base_ref }}"
          git fetch origin ${{ github.base_ref }} || true
          echo "Changed Swift files:"
          git diff --name-only origin/${{ github.base_ref }}...HEAD | grep "\.swift$" || echo "No changes detected"
      - name: GitHub Action for SwiftLint
        uses: 0tak2/action-swiftlint@3.2.3
        env:
          WORKING_DIRECTORY: QueenCam
          DIFF_BASE: ${{ github.base_ref }}
